# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# training settings
epochs: 800
train_batch_size: 256
learner: adam
learning_rate: 0.0001
neg_sampling: ~
eval_step: 10
stopping_step: 20
clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.01

# evaluation settings
eval_args:
  split: {'LS':'valid_and_test'}
  group_by: user
  order: TO
  mode: pop100
repeatable: True
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
topk: [1,5,10,20]
valid_metric: NDCG@10
valid_metric_bigger: True
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4

# model
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
mask_ratio: 0.6
loss_type: 'CE'

# dataset
# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
##关键1
seq_len: ~
# Label for Point-wise DataLoader
LABEL_FIELD: label
# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_
# Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
# Selectively Loading
load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id, categories]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: "first"
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Preprocessing
alias_of_user_id: ~
alias_of_item_id: ~
alias_of_entity_id: ~
alias_of_relation_id: ~
preload_weight: ~
normalize_field: ~
normalize_all: True